version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/
  webserver:
    image: nginx:alpine
    container_name: my-nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
